Repository googleapis/nodejs-ai-platform, pull requests merged in 2020-11, with the labels that each got.

#8 chore: adds Cloud AI DPE to CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes, cla: yes

#7 build: update linkinator links
  linkinator.config.json
  synth.metadata
Labels: automerge, cla: yes, cla: yes, context: none

#10 built: add custom env vars
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/pre-samples-test.sh
  .kokoro/presubmit/node12/samples-test.cfg
  synth.py
Labels: cla: yes, cla: yes

#11 build: update protos.json
  protos/protos.json
  synth.metadata
Labels: cla: yes, cla: yes, context: none

#19 chore: address linting issue
  src/v1beta1/job_service_client.ts
  src/v1beta1/migration_service_client.ts
  src/v1beta1/model_service_client.ts
  src/v1beta1/pipeline_service_client.ts
  synth.metadata
Labels: cla: yes, cla: yes, context: none

#21 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: automerge, cla: yes, cla: yes, context: full
