Repository googleapis/nodejs-ai-platform, pull requests merged in 2020-12, with the labels that each got.

#23 chore: generate GAPIC metadata JSON file
  src/v1beta1/gapic_metadata.json
  synth.metadata
Labels: cla: yes, cla: yes, context: full

#24 chore: fixing syntax error in the GAPIC metadata JSON file
  src/v1beta1/gapic_metadata.json
  synth.metadata
Labels: cla: yes, cla: yes, context: full

#22 feat: adds enhancements to library
  .gitignore
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  README.md
  linkinator.config.json
  package.json
  samples/README.md
  samples/create-training-pipeline-image-classification.js
  samples/list-endpoints.js
  samples/package.json
  samples/predict-image-classification.js
  samples/resources/daisy.jpg
  samples/test/create-training-pipeline-image-classification.test.js
  samples/test/predict-image-classification.test.js
  samples/test/quickstart.test.js
  src/decorator.ts
  src/enhanced-types.json
  src/helpers.ts
  src/index.ts
  src/value-converter.ts
  synth.metadata
  synth.py
  test/helpers.test.ts
  test/index.test.ts
  tsconfig.json
Labels: cla: yes, cla: yes

#30 docs: updates to README based on new samples
  .gitignore
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  linkinator.config.json
  samples/README.md
  synth.metadata
Labels: cla: yes, cla: yes, context: none

#31 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: automerge, cla: yes, cla: yes, context: full
