Repository googleapis/nodejs-ai-platform, pull requests merged in 2021-03, with the labels that each got.

#81 fix: adds index.ts to excludes
  synth.py
Labels: api: aiplatform, cla: yes, cla: yes

#89 build: update gapic-generator-typescript to v1.2.10
  src/index.ts
  synth.metadata
  webpack.config.js
Labels: cla: yes, cla: yes, context: partial

#91 build: stop providing hint for default_version
  synth.metadata
  synth.py
Labels: automerge, cla: yes, cla: yes
