Repository googleapis/nodejs-ai-platform, pull requests merged in 2021-02, with the labels that each got.

#66 chore: update CODEOWNERS config
  .repo-metadata.json
Labels: cla: yes, cla: yes

#65 samples: fix region tag
  samples/predict-text-sentiment-analysis.js
Labels: cla: yes, cla: yes, samples

#72 lint: tweaks to formatting of JSON
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  README.md
  samples/README.md
  src/v1/dataset_service_client_config.json
  src/v1/endpoint_service_client_config.json
  src/v1/gapic_metadata.json
  src/v1/job_service_client_config.json
  src/v1/migration_service_client_config.json
  src/v1/model_service_client_config.json
  src/v1/pipeline_service_client_config.json
  src/v1/prediction_service_client_config.json
  src/v1/specialist_pool_service_client_config.json
  src/v1beta1/dataset_service_client_config.json
  src/v1beta1/endpoint_service_client_config.json
  src/v1beta1/gapic_metadata.json
  src/v1beta1/job_service_client_config.json
  src/v1beta1/migration_service_client_config.json
  src/v1beta1/model_service_client_config.json
  src/v1beta1/pipeline_service_client_config.json
  src/v1beta1/prediction_service_client_config.json
  src/v1beta1/specialist_pool_service_client_config.json
  synth.metadata
Labels: automerge, cla: yes, cla: yes, context: partial

#78 fix: extend test timeout
  samples/package.json
Labels: cla: yes, cla: yes

#82 Rename apiEndpoint for samples
  samples/predict-custom-trained-model.js
  samples/predict-image-classification.js
  samples/predict-image-object-detection.js
  samples/predict-tabular-classification.js
  samples/predict-tabular-regression.js
  samples/predict-text-classification.js
  samples/predict-text-entity-extraction.js
  samples/predict-text-sentiment-analysis.js
Labels: api: aiplatform, cla: yes, cla: yes, samples
